# A unique name, must eq var console/vite.config.js#pluginEntryName,
# and can not contain specific symbol such as - .
name: PluginBaiDuPan
# plugin entry class that extends BasePlugin
clazz: run.ikaros.plugin.baidupan.BaiDuPanPlugin
# plugin 'version' is a valid semantic version string (see semver.org).
version: 0.1.2
requires: ">=0.3.0"
author:
  name: Ikaros OSS Team
  website: https://github.com/ikaros-dev
logo: https://ikaros.run/logo.png
homepage: https://github.com/ikaros-dev/plugin-baidupan
displayName: "百度网盘"
description: "百度网盘插件，将百度网盘作为远端"
license: "AGPL-3.0"